### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] 无法联机，因为目标计算机拒绝联机

### ISSUE THREAD

**Issue by marco302** [FutunnOpen/futuquant#10]
请问服务器是不是维护?

>>>from futuquant.open_context import *
>>>quote_ctx = OpenQuoteContext(host='119.29.141.202', port=11111)
ConnectionRefusedError: [WinError 10061] 无法联机，因为目标计算机拒绝联机。
ConnectionRefusedError: [WinError 10061] 无法联机，因为目标计算机拒绝联机。

**Comment by FutunnOpen** [comment]
已完成维护，请您重新尝试连接。非常抱歉。
