### ISSUE TITLE
怎样让FutuOpenD在后台运行，因为 有一步是输入短信验证码？

### ISSUE THREAD

**Issue by westeast** [FutunnOpen/futuquant#101]

**Comment by summer-wu** [comment]
验证码只第一次输入，第二次第三次第N此都不用输入。
+ unix-like用`nohup ./FutuOpenD &> FutuOpenD.log &`
+ windows只能用`./FutuOpenD -console=0`，缺点是看不到log了

**Comment by westeast** [comment]
@summer-wu 好的多谢谢~，自己写的example可以 提到futu example里面吗？
