### ISSUE TITLE
未同意免責聲明

### ISSUE THREAD

**Issue by denpoon** [FutunnOpen/futuquant#108]
我行FutuOpenD.exe  . 它跟著發了個SMS 密碼給我. 我在 FutuOpenD.exe 的視窗輸入 input_phone_verify_code -code=413209 
它跟著回   
登入成功 ......
...
....
A 股市 ..... 正常
未同意免責聲明
FutuOpenD已退出

請問. 我怎麼可以"同意免責聲明"

**Comment by EGBAR** [comment]
See Q&A below:
https://help.futu5.com/faq/topic2410
