### ISSUE TITLE
港股5月份資料不全

### ISSUE THREAD

**Issue by umumpaul** [FutunnOpen/futuquant#111]
在futuquant下了kday發現港股5月份資料不全
都沒有5月7日的..但那天不是假期..

**Comment by FutunnOpen** [comment]
get_history_kline（）可以查询到5月7日的港股日K数据，如下：
code             time_key    open   close        high         low   pe_ratio  turnover_rate    volume      turnover  change_rate  last_close
0  HK.00700  2018-05-07 00:00:00  387.12  379.12  387.919988  374.519994  41.657001          0.361  34266791  1.306100e+10    424.05177   72.343998
