### ISSUE TITLE
message Ticker 裡中的 required int32 dir = 3  怎樣理解?

### ISSUE THREAD

**Issue by denpoon** [FutunnOpen/futuquant#118]
Qot_GetTicker.proto 裡的
message Ticker 裡中的 required int32 dir = 3; //TickerDirection, 买卖方向
是什麼意思?  數值好像有 1, 2, 3 怎樣理解?

**Comment by FutunnOpen** [comment]
主动买入， 主动卖出， 平盘， 对应牛牛客户端UI表现的上升，下降箭头 和 *
