### ISSUE TITLE
Qot_GetTicker.proto 裡 message Ticker 中的 required string time = 1;  能顯示 千分之一秒嗎? 

### ISSUE THREAD

**Issue by denpoon** [FutunnOpen/futuquant#119]
message Ticker 裡中的 required string time = 1;  能顯示 千分之一秒嗎?  現在只顯示到 秒, 不夠啊!

**Comment by FutunnOpen** [comment]
CS新协议会支持，  会同支持 期货行情的版本一起发布， 时间初步定在下半年。
