### ISSUE TITLE
2016-02-02日K线数据有成交量，成交额却为0

### ISSUE THREAD

**Issue by yorgee571** [FutunnOpen/futuquant#13]
1，2016-02-02日K线数据有成交量，成交额却为0
     如 US.AAC  US.ACP 等等，很多

2， 2016-02-02日K线数据中有两只股有多条记录
   US.AAPL  --- 25 条    
   US.SOHU  --- 25条

QQ：262429350

**Comment by FutunnOpen** [comment]
历史数据问题， 已提单跟进
