### ISSUE TITLE
Undefined name 'stk_code' in get_realtime_data.py

### ISSUE THREAD

**Issue by cclauss** [FutunnOpen/futuquant#130]
<sub>https://github.com/FutunnOpen/futuquant/blob/master/futuquant/examples/learn/get_realtime_data.py#L17</sub>

[flake8](http://flake8.pycqa.org) testing of https://github.com/FutunnOpen/futuquant on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./futuquant/examples/learn/get_realtime_data.py:17:30: F821 undefined name 'stk_code'
        print("%s %s: %s" % (stk_code, "QUOTE", ret_data))
                             ^
1     F821 undefined name 'stk_code'
1
```

**Comment by loadatom** [comment]
已修复 de426f88c0261927075077b3c8fbc65242f719b1
