### ISSUE TITLE
mac 下使用 127.0.0.1 无法连接

### ISSUE THREAD

**Issue by cybercall** [FutunnOpen/futuquant#14]
如题,在mac 下使用 127.0.0.1 无法连接,只能使用云端服务器.

**Comment by FutunnOpen** [comment]
ip不对， 要把127.0.0.1 改成你云端的服务器ip

**Comment by freemancfwong** [comment]
請問云端服务器ip指的是什幺？是我現在macbook上网的ip地址嗎？感謝！

**Comment by xain** [comment]
我估计这个接口是要自己运行一个带服务功能的特殊客户端的。这个客户端转发信息。从视频上看这个客户端好像只有windows版本。

**Comment by chuckding** [comment]
是用你的Windows的运行富途，然后自己搭一个云服务器，用mac连接这个服务器。就能在mac上用了

**Comment by freemancfwong** [comment]
@xain 是的。今天也有問到。我之前用一般的牛牛客戶端所以用什麼ip都不对，是应該要用富途API的QQ群里「文件」所出示的API專用客戶端，才能在python中呼叫API接口。我有點不明白為什麼这个專用客戶端要放在QQ群里而不是這里或是document网站中⋯⋯这造成了一定的不便⋯⋯另一点更不明白是為什幺只有windows版專用客戶端⋯⋯明明100%的开發者都是在mac/linux环境下工作的吧⋯⋯

**Comment by xain** [comment]
只有windows版真的超级不方便。起码应该要有linux的。我今天才开始了解到富途有api，不明白为什么要经过一个本地的客户端？而不是由富途提供一个直接的API接口？

**Comment by freemancfwong** [comment]
@xain 經過本地客戶端我認為情有可原，这樣可以直接用上客戶端里的定义而不需要再另寫一套，也有助於使图像客戶端和API功能達到一致。而且留意API的工作流程介紹中也暗示了API捉取數據前会先檢查本地有沒有相应數據可以直接取用，这表明有需要先經過客戶端。

但是沒有linux版本这我真心不懂。要加入QQ群才能拿到API專用客戶端这件事也顯得整个計劃的格局不夠大⋯⋯

**Comment by xain** [comment]
数据获取、缓存和数据可视化可以让用户自己想办法解决，这个不应该是API的功能。

如果有一个可以直接可以使用的在线API，只要提供基础的功能，如当前价格和下单交易即可以了。如担心压力过大，服务器可以限定访问频度。

**Comment by freemancfwong** [comment]
有道理。希望未來会朝著更好的方向走

**Comment by FutunnOpen** [comment]
支持 跨平台的api平台还在技术重构中， 敬请期待~
