### ISSUE TITLE
[sync_network_manager.py] _socket_create_and_loop_connect:193: wait to connect FutuOpenD

### ISSUE THREAD

**Issue by haiouzsf** [FutunnOpen/futuquant#143]
FutuOpenD.exe 运行正常：

_FutuOpenD运行中
加载配置文件成功
服务器启动
API监听地址: 127.0.0.1:11111
Telnet监听地址: 127.0.0.1:22222
登录方式:帐号密码登录
正在登录
登录帐号:xxxxxxx
主连接:香港接入点1 次连接:香港接入点2
登录成功
OpenAPI用户等级:二级用户
港股市场:Lv2,权限状态:正常
美股市场:Lv1,权限状态:正常
A股市场:Lv1,权限状态:正常
必要数据准备完毕
港股市场:Bmp,权限状态:权限被踢
港股市场:Lv2,权限状态:正常
美股市场:Lv1,权限状态:正常
A股市场:Lv1,权限状态:正常

FutuOpenD version 1.03, FTNN 客户端运行正常，两者同时打开着。

运行一下代码：

# 导入futuquant api
import futuquant as ft

# 实例化行情上下文对象
quote_ctx = ft.OpenQuoteContext(host="127.0.0.1", port=11111)

报错：
**[sync_network_manager.py] _socket_create_and_loop_connect:193: wait to connect FutuOpenD**

**Comment by haiouzsf** [comment]
我的解决办法：
将FTNN 客户端关闭，将FutuOpenD version 1.03重启，然后错误就不存在了；可能是FTNN使用的port 11111与FutuOpenD 使用了同一个port，导致FutuOpenD 链接不上。

**Comment by loadatom** [comment]
需要升级futuquant，sync_network_manager是较老版本的内容
