### ISSUE TITLE
港股只能調到三年前或以內的小時K線紀錄嗎

### ISSUE THREAD

**Issue by ivanfong01** [FutunnOpen/futuquant#144]
2016-09-20 以前的數據一直為空...

**Comment by kevinzhengyang** [comment]
恰好刚刚做过，可以取HK.00700从上市至今全部数据。
 
环境： Ubuntu Server 16.04， FutuOpenD（v1.03） + FutuHistData + futuquant（v3）+Python3.6

我用的方法，仅供参考:

    def get_hist_kline(self, code:'交易代码', ktypes:'K线类型列表' = [ft.KLType.K_DAY]):
        ''' 下载补全历史数据 '''

        start_time = ''
        context = ft.OpenQuoteContext(host=self._ip, port=self._port)
        logger.info('context opened for %s', code)
        datafile = self._path + code + '.h5'
        with pd.HDFStore(datafile, 'a') as store:
            for ktype in ktypes:
                #print('ktype=',ktype)
                # HDFStore的key是按照路径设置的，有'/'前缀
                #print('keys=', store.keys())
                df = store[ktype] if ('/' + ktype) in store.keys() else None
                if (df is None) or df.empty:
                    # 数据不存在，获取股票上市时间
                    ret, snap = context.get_market_snapshot(code)
                    if (ft.RET_OK == ret):
                        start_time = snap.tail(1)['listing_date'].values[0][:10]
                        print('listing_date =', start_time)
                    else:
                        start_time = '1998-01-01'
                        print('default date=', start_time)
                else:
                    logger.info('%s loaded', code)
                    end_time = df.tail(1)['time_key'].values[0][:10]
                    start_time = (dt.datetime.strptime(end_time, '%Y-%m-%d')
                                    + dt.timedelta(days=1)).strftime('%Y-%m-%d') # 下个交易日取日历一天后

                    print('load_time', start_time)

                # 从start_time开始下载
                while True:
                    logger.debug('%s %s start_time=%s', code, ktype, start_time)
                    print('{} {} start_time={}'.format(code, ktype, start_time))
                    ret, snap = context.get_history_kline(code, start_time, None, ktype)
                    if (ft.RET_OK == ret) and not snap.empty: # 数据获取成功
                        store.append(ktype, snap) # 增加数据
                        print('{} {} append'.format(code, ktype))
                        end_time = snap.tail(1)['time_key'].values[0][:10]
                        start_time = (dt.datetime.strptime(end_time, '%Y-%m-%d')
                                      + dt.timedelta(days=1)).strftime('%Y-%m-%d') # 下个交易日取日历一天后
                        continue # 继续获取新一年的数据
                    else:
                        logger.info('%s hist %s kline ok', code, ktype)
                        print('{} {} ok'.format(code, ktype))
                        break
            store.close()
        context.close()

**Comment by ivanfong01** [comment]
我忘了說，我是指小時K線

**Comment by loadatom** [comment]
60分k线也是只提供近2年的。

**Comment by loadatom** [comment]
超过2星期无更新，关闭
