### ISSUE TITLE
Bug: API接口get_market_snapshot实际返回字段少于文档说明

### ISSUE THREAD

**Issue by kevinzhengyang** [FutunnOpen/futuquant#145]
环境 FutuOpenD（Ubuntu 1.03）+fuququant（3.0） 
调用get_market_snapshot接口，传入'HK.00700‘，得到的返回结果与文档说明相比，缺少如下字段：
equity_valid
issued_shares
pe_ttm_ratio

stock_owner

option_valid字段以下全部

**Comment by towerd** [comment]
需要升级futuquant，有些字段是后面加的

**Comment by loadatom** [comment]
需要升级futuquant，有些字段是后面加的
