### ISSUE TITLE
About the development progress

### ISSUE THREAD

**Issue by TonyQuant** [FutunnOpen/futuquant#147]
Do you have a time table that the following items will be available:

1. Stock Index options data  (including snapshot, ticker and bid/ask)
2. Stock options data (including snapshot, ticker and bid/ask)

**Comment by loadatom** [comment]
是实时行情还是历史数据？

**Comment by TonyQuant** [comment]
我看到已推出美國股票期權的實時數據，但香港的指數期權和股票期權還沒有，請問什麼時候會推出？

**Comment by FutunnOpen** [comment]
香港期权和股票期权暂时没有时间表
