### ISSUE TITLE
不想应交易的回调函数

### ISSUE THREAD

**Issue by hellobiek** [FutunnOpen/futuquant#155]
futuquant/futuquant/examples/learn/check_all_get_push.py
中测试交易的回调函数，发现

class TradeOrderTest(TradeOrderHandlerBase):
    """ order update push"""
    def on_recv_rsp(self, rsp_pb):
        ret, content = super(TradeOrderTest, self).on_recv_rsp(rsp_pb)
        if ret == RET_OK:
            print("*** TradeOrderTest content={}\n".format(content))
        return ret, content

class TradeDealTest(TradeDealHandlerBase):
    """ order update push"""
    def on_recv_rsp(self, rsp_pb):
        ret, content = super(TradeDealTest, self).on_recv_rsp(rsp_pb)
        if ret == RET_OK:
            print("*** TradeDealTest content={}".format(content))
        return ret, content

def main():
    trd_ctx = OpenCNTradeContext(host='127.0.0.1', port=11111)
    trd_ctx.set_handler(TradeOrderTest())
    trd_ctx.set_handler(TradeDealTest())
    trd_ctx.start()
    ret_code, ret_data = trd_ctx.place_order(1.6, 100, "SH.601258", trd_side = TrdSide.BUY, trd_env = TrdEnv.SIMULATE)
    sleep(20)
    trd_ctx.close()

发现TradeOrderTest可以响应，但是TradeDealTest不能响应。

结果如下：

 TradeOrderTest content=    trd_env       code stock_name  dealt_avg_price  dealt_qty    qty    ...     order_status          create_time         updated_time trd_side last_err_msg trd_market
0  SIMULATE  SH.601258       庞大集团              0.0        0.0  100.0    ...       SUBMITTING  2018-10-30 13:35:03  2018-10-30 13:35:03      BUY                      CN
[1 rows x 15 columns]

 TradeOrderTest content=    trd_env       code stock_name  dealt_avg_price  dealt_qty    qty    ...     order_status          create_time         updated_time trd_side last_err_msg trd_market
0  SIMULATE  SH.601258       庞大集团              1.5      100.0  100.0    ...       FILLED_ALL  2018-10-30 13:35:03  2018-10-30 13:35:05      BUY                      CN
[1 rows x 15 columns]

问题：
TradeOrderTest订单已经完全满足回调，但是TradeDealTest一直不能响应。
环境：
FutuOpenD版本信息:1.04.207体验版
futuquant          3.3.1

**Comment by FutunnOpen** [comment]
模拟交易不支持成交回调， 实盘可以
