### ISSUE TITLE
希望能开发Mac/Linux 版本

### ISSUE THREAD

**Issue by bowenli86** [FutunnOpen/futuquant#2]
Hi 您好,

请问什么时候考虑开发 Mac/Linux版本? 现在 quant api 只支持 windows 版本, 对程序开发者来说很不方便.

谢谢!

**Comment by FutunnOpen** [comment]
如果您想要在Linux或Mac上编写使用API的程序，可以在一台windows主机或虚拟机上搭建富途牛牛的伪服务器，然后在Linux或Mac上写代码访问伪服务器。

**Comment by ruanyl** [comment]
@FutunnOpen 有计划开发OSX版的API吗？

**Comment by FutunnOpen** [comment]
@ruanyl 有的

**Comment by marco302** [comment]
请问服务器是不是维护?
ConnectionRefusedError: [WinError 10061] 无法联机，因为目标计算机拒绝联机。

**Comment by minghongtao** [comment]
mac版本的确实非常有必要，现在上班都是用mac了

**Comment by FutunnOpen** [comment]
感谢您的反馈，正在计划添加其他平台。
