### ISSUE TITLE
有没有更加详细一些的新手指引？

### ISSUE THREAD

**Issue by Reekin** [FutunnOpen/futuquant#37]
我刚开始接触量化，官网的三个视频教程已经看完了，但感觉课程一直在盯着api讲，到现在还是不太清楚一个从构建策略到实际运行完整的操作流程应该是怎样的。
比如我想构建一个代替我盯盘的策略，是直接在项目中新建一份py写策略吗？写完策略后想要长期运行，是在main里写个for循环直接右键运行一下就可以了吗？

**Comment by eyelivermore** [comment]
我还在搭建环境中迷茫

**Comment by chuckding** [comment]
参考下futuquant中的tinyquant，有点Python基础就能好理解了

**Comment by FutunnOpen** [comment]
顶楼上， tinyquant是近期加的一个实盘范例， 后续会再增加回测的范例
