### ISSUE TITLE
希望增加牛熊回收价、行权日、溢价、交易量字段的获取

### ISSUE THREAD

**Issue by Reekin** [FutunnOpen/futuquant#38]

**Comment by eyelivermore** [comment]
希望增加牛熊回收价、行权日、溢价、交易量字段的获取

**Comment by FutunnOpen** [comment]
获取市场快照 get_market_snapshot 接口有： wrt_recovery_price: 窝轮回收价 /  wrt_maturity_date: 格式化窝轮到期时间/  wrt_premium: 窝轮溢价 /  volume： 成交数量
