### ISSUE TITLE
对交易快捷键的一些建议

### ISSUE THREAD

**Issue by onfeelings** [FutunnOpen/futuquant#39]
由于每个股的一手的手数不一样,因此建议常用股数那里设置成常用手数,或者加上常用固定金额的快捷键,如下图. 还有的是能不能在交易窗口上添加一个快捷键,使之能直接换股票号码,而不用鼠标点击才能换号码,因为这对本人的操作速度影响很大,希望能尽快改进这方面的问题因为涉及到实际交易望重视
![lck j jo9 p6fxshm dt7 r](https://user-images.githubusercontent.com/22488948/34432580-83c355de-ecb3-11e7-968a-910456dc7755.png)
.
![e g 2z6x401pezuq1ws1mv4](https://user-images.githubusercontent.com/22488948/34432516-e7a72aae-ecb2-11e7-893a-004c2e9ca04b.png)
![2c45z8wco 3p97 iqbs](https://user-images.githubusercontent.com/22488948/34432517-e9ae346e-ecb2-11e7-8703-0e51903c14de.png)

**Comment by FutunnOpen** [comment]
已反馈给pc 的产品经理， 后续有问题也可以在客户端上直接反馈， 入口： 菜单 -》 帮助 -》意见反馈
![image](https://user-images.githubusercontent.com/25790136/34940691-7cb362e0-fa2b-11e7-86c9-ad5708f8a592.png)
