### ISSUE TITLE
 UnicodeEncodeError: 'gbk' codec can't encode character '\u01bd' in position 40: illegal multibyte sequence

### ISSUE THREAD

**Issue by groey** [FutunnOpen/futuquant#42]
在安装futuquant的时候报错， UnicodeEncodeError: 'gbk' codec can't encode character '\u01bd' in position 40: illegal multibyte sequence

![image](https://user-images.githubusercontent.com/23619872/34600415-4c3eec34-f232-11e7-9eba-a8e1f9047da8.png)
 请问如何解决这个问题?

**Comment by FutunnOpen** [comment]
2.3.9 更新了新pip包， 再试下
