### ISSUE TITLE
Illegal byte sequence when install version 2.3.7 or 2.3.8

### ISSUE THREAD

**Issue by hujb2000** [FutunnOpen/futuquant#44]
pip install futuquant==2.3.7 or 2.3.8

OSError: [Errno 92] Illegal byte sequence: '/private/var/folders/hp/l6xkn4bd0fg7c10cnzh3f9vr0000gn/T/pycharm-packaging779/futuquant/futuquant/examples/vnpy/Windows ƽ̨\udcb0\udcb2װ MongoDB.url'

**Comment by FutunnOpen** [comment]
2.3.9 更正， 文件名包括中文导致的问题
