### ISSUE TITLE
虚拟机环境下无法下载历史K线数据

### ISSUE THREAD

**Issue by rui-liu** [FutunnOpen/futuquant#50]
在VirtualBox和青云的云主机上都有此问题。尝试过的Windows版本包括windows 10和server 2016。

完成ftplugin.ini配置后，FTHistData.exe无法自动启动，即使手动启动后也无法下载K线数据，下载进度始终停留在0.0%。ftplugin.ini配置如下：
```
[pluginhost]
download_hist_enable=1
download_hist_time_start=0600
download_hist_time_end=2300
download_market=hk|cn|us
download_kline_type=day|week|month
```

**Comment by gaussleescorpio** [comment]
I have the similar problem not in a virtual guest windows 10. Please help us solve it.

**Comment by FutunnOpen** [comment]
请使用新版本：https://www.futunn.com/download/openAPI。
