### ISSUE TITLE
_send_async_req 报错

### ISSUE THREAD

**Issue by leonlazuli** [FutunnOpen/futuquant#51]
def _send_sync_req(self, req_str):
        """
        send a synchronous request
        """
        ret, msg, content = self._sync_net_ctx.network_query(req_str)
        if ret != RET_OK:
            return RET_ERROR, msg, None
        return RET_OK, msg, content

    def _send_async_req(self, req_str):
        """
        send a asynchronous request
        """
        if self._async_ctx:
            self._async_ctx.send(req_str) #LEON
            return RET_OK, ''
        return RET_ERROR, 'async_ctx is None!'

async方法里面，是直接发送的req_str， 到asyncore.py库里会报 str不能和bytes concat的错误。  但是上面的sync方法里，network_query这个方法里做了str2binary。    这里是不是有问题？

**Comment by leonlazuli** [comment]
又看了下代码，应该是调用 self._async_ctx.network_query(req_str)  而不是 self._async_ctx.send(req_str)  ?

**Comment by FutunnOpen** [comment]
python3.x 的兼容问题， pip已更新刚才2.3.13
