### ISSUE TITLE
历史数据还是需要好好整理下

### ISSUE THREAD

**Issue by luwening** [FutunnOpen/futuquant#59]
1. 按照配置文件里面说明，可是设置了year，也不能，提示不存在
;可选的K线类型为day、week、month、year、min1、min5、min15、min30、min60，多个类型用|连接
2. 日K历史
目前看最早就到2000年开始，是不是可以增加到股票上市以来的所有的记录
3. 周K，月K的时间就更加短了，看基本从2017年开始的
虽然自己可以根据日K转化，但是如果直接提供了就更加方便了

**Comment by FutunnOpen** [comment]
1. year 的目前 暂时无数据， 后续更正说明 
2.  日k数据源的限制
3. 暂时开放数据的限制， 后续会考虑放开

**Comment by luwening** [comment]
这就奇怪了，1，2说数据源的限制也就罢了
3竟然也会有问题。。。太敷衍了。。。
