### ISSUE TITLE
SZ.002739日K线2017-06-22收盘价有疑问

### ISSUE THREAD

**Issue by shiquanwang** [FutunnOpen/futuquant#60]
SZ.002739日K线2017-06-22收盘价为51.95
[新浪财经](http://finance.sina.com.cn/realstock/company/sz002739/nc.shtml)查到的数据是51.93
通过Tushare查到的也是51.93

**Comment by FutunnOpen** [comment]
已记录排期跟进

**Comment by loadatom** [comment]
已交给相关同事修复
