### ISSUE TITLE
分钟线数据与日线数据有差异

### ISSUE THREAD

**Issue by shiquanwang** [FutunnOpen/futuquant#65]
查了沪深300的股票和一些指数(SH.000300, SH.000001, SH.000905, SH.000016, SZ.399001)
时间范围是2017-02-03到2018-02-28
使用1分钟线的数据生成日线，然后和直接查询到的日线数据进行比较
* open: 没有差异
* close: 没有差异
* high: 有差异
* low: 有差异
* turnover: 有差异
* volume: 有差异

记录下来了high, low有差异的项，贴在[GIST](https://gist.github.com/shiquanwang/3516127ae07260830f243ab6f7a5bd33)了

做了简单的统计
* 指数
  - low: 756条差异，差异的均值-0.1627，差异的标准差0.1644
  - high: 709条差异，差异的均值0.1520，差异的标准差0.1354
* 股票
  - low: 7499条差异，差异的均值-0.0257，差异的标准差0.0649
  - high: 7904条差异，差异的均值0.0203，差异的标准差0.0377

**Comment by zivzhou89** [comment]
可否分享下你合并分钟线的代码？

**Comment by loadatom** [comment]
已交给相关同事修复
