### ISSUE TITLE
怎样通过talib得到futu的pc客户端的kdj指标的值

### ISSUE THREAD

**Issue by 3xp10it** [FutunnOpen/futuquant#70]
网上流传的通过talib获取kdj指标的k,d值的关键代码如下:
```
        k,d = talib.STOCH(high=high, 
                        low=low, 
                        close=close,
                        fastk_period=9,
                       slowk_period=3,
                       slowk_matype=0,
                       slowd_period=3,
                       slowd_matype=0
        )
```
但是这样得到的结果和futu的pc客户端的kdj指标的结果不一样,网上有人说要将futu的pc客户端的kdj的计算方法中的SMA修改成MA,不知应该怎么修改.现有以下2个方案:
1.修改上面代码中的k,d的通过tabli获取的方法(估计是修改slowk_matype和slowd_matype参数)
2.修改futu的pc客户端的kdj的计算公式

请教下这两种方法该怎么做才能得到futu的pc客户端的kdj的值与代码得到的值相等的结果?

[参考1][1],[参考2][2],[参考3][3]

[1]: https://www.joinquant.com/post/142
[2]: https://www.joinquant.net/post/453?tag=faq
[3]: https://www.ricequant.com/community/topic/380/

**Comment by loadatom** [comment]
太久远的问题，关闭
