### ISSUE TITLE
安裝 futuquant 出現錯誤

### ISSUE THREAD

**Issue by edwmin** [FutunnOpen/futuquant#72]
在window 7 環璄下 運行 pip install futuquant

Collecting futuquant
  Using cached futuquant-2.3.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User1\AppData\Local\Temp\pip-install-awnd8bj1\futuquant\set
up.py", line 20, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\User1\Ap
pData\Local\Temp\pip-install-awnd8bj1\futuquant\

python version is 3.6.5
請問那裏出現問題?

**Comment by williamjie** [comment]
https://stackoverflow.com/questions/25192794/no-module-named-pip-req
pip 版本问题啦；

**Comment by FutunnOpen** [comment]
futuquant 的setup.py已fix , 请使用futuquant3.x最新版本
