### ISSUE TITLE
能否增加道琼斯和纳指的指数期货数据?

### ISSUE THREAD

**Issue by onfeelings** [FutunnOpen/futuquant#74]
功能能做到像恒生期指当月999010一样吗?

**Comment by fatfatson** [comment]
@onfeelings 你在富途api里能获取到999010的行情数据吗？？

**Comment by onfeelings** [comment]
可以的

**Comment by FutunnOpen** [comment]
注意用正确的代码： HK_FUTURE.999010  、  US..DJI    、US..IXIC
