### ISSUE TITLE
pip10.0没办法安装，需要对pip降级才能完成安装

### ISSUE THREAD

**Issue by shenshaohui1991** [FutunnOpen/futuquant#76]
rt

**Comment by edwmin** [comment]
降級到那一個版本？謝

**Comment by williamjie** [comment]
https://stackoverflow.com/questions/25192794/no-module-named-pip-req
这里有解决办法

**Comment by summer-wu** [comment]
我使用pip9.0.1+python3.6可以安装。用的venv环境

**Comment by loadatom** [comment]
python 3.7 + pip 10.0.1可以安装。很久没新讨论，关闭
