### ISSUE TITLE
price not in broker data

### ISSUE THREAD

**Issue by chanpl** [FutunnOpen/futuquant#77]
現在broker data不含檔位價格, 能加嗎?

現在broker dataframe 是這樣的:

| n | bid_broker_id | bid_broker_name | bid_broker_pos |
| - | ------------- | --------------- | -------------- |
| 0 | 8136          | 中銀國際        | 0              |
| 1 | 5882          | 信達國際        | 0              |
| 2 | 8932          | 創興            | 1              |
| 6 | 8136          | 中銀國際        | 2              |

希望能把價格包含其中:

| n | bid_broker_id | bid_broker_name | bid_broker_pos | bid_broker_price|
| - | ------------- | --------------- | -------------- | --------------- |
| 0 | 8136          | 中銀國際        | 0              | 1.12            |
| 1 | 5882          | 信達國際        | 0              | 1.12            |
| 2 | 8932          | 創興            | 1              | 1.11            |
| 6 | 8136          | 中銀國際        | 2              | 1.10            |

**Comment by FutunnOpen** [comment]
收到您的需求反馈，已记录
