### ISSUE TITLE
板块的k线历史数据为空

### ISSUE THREAD

**Issue by MarStarck** [FutunnOpen/futuquant#78]
如code=HK.BK1001这种版块的，

`_, prices = quote_ctx.get_history_kline(code, start=pre_day, ktype='K_DAY', fields=[KL_FIELD.CLOSE])`
返回一个空的dataframe
只有code=HK.00700这种股票的就行。

不知道是bug还是目前不支持板块的历史数据查询？

另外想问下历史数据除了k线，还有rsi等其他指标可以获取吗？

**Comment by arthurlirui** [comment]
历史数据能够拿到多少精度的

**Comment by FutunnOpen** [comment]
1、历史K线不支持板块查询。
2、暂无指标数据。
