### ISSUE TITLE
支持下mac系统可以吗

### ISSUE THREAD

**Issue by yongtaof** [FutunnOpen/futuquant#79]
可以支持下mac系统吗

**Comment by williamjie** [comment]
好像18年6月份有API版本；

**Comment by bowenli86** [comment]
到底啥时候才能支持一下？

**Comment by totalwei** [comment]
@bowenli86 
最近大伙非常的关心我们的新版的**内测**时间，在此统一告知大家，2018/06/05是我们内测上线时间，届时我们会将新版本上传到群共享里，欢迎大家积极体验。
新版本最关键的特性：脱离了原来的富途牛牛PC端，可以独立运行，支持Windows、Linux、Mac三大平台！

**Comment by zhujl1991** [comment]
能不能批准下进入qq群。。期待mac版

**Comment by jinwei233** [comment]
什么时候有对外发布的版本?

**Comment by Gwill** [comment]
支持了，可以关掉这个 issue 了

**Comment by FutunnOpen** [comment]
FutuOpenD已支持
