### ISSUE TITLE
3.0版本建议去掉debug的输出

### ISSUE THREAD

**Issue by tenfyzhong** [FutunnOpen/futuquant#82]
3.0版本建议去掉debug的输出

![image](https://user-images.githubusercontent.com/5044825/41075560-b88bdad4-6a3f-11e8-8261-258714b85e3c.png)

**Comment by summer-wu** [comment]
把futuquant/common/ft-logger.py中的log_level改为WARN就好了

**Comment by FutunnOpen** [comment]
新版本已调整
