### ISSUE TITLE
TradeDealHandler永远不会被调用

### ISSUE THREAD

**Issue by summer-wu** [FutunnOpen/futuquant#99]
# TradeDealHandler永远不会被调用
今天我有futuquant交易了60笔订单，收到了0个callback。

我稍微看了下跟回调相关的python代码，核心代码位于`common/handler_context.py和common/network_manager.py`中。
逻辑如下：
+ HandlerContext中_handler_table字典，其中记录了type(类)、obj（类示例）
+ 在set_handler时，遍历type，用传入的handler覆盖掉默认的obj。
+ 在recv_func中，根据proto_id找到obj。
+ NetManager中有个死循环，循环调用poll，poll发现socket有数据，则解析数据，将解析的数据穿个recv_func

所以，handler不被调用有两种可能：1、server没给openD发 2、openD没给client发 3、client收到了没处理

_handler_table中proto_id对应关系：
+ TradeOrderHandler的proto_id是2208
+ TradeDealHandler 的proto_id是2218

搜索一下log，发现确实是openD没发，因为根本就没有找到`ProtoID=2218`。用下面的命令可以找出。
```
$ cd ~/.com.futunn.FutuOpenD/Log
$ grep -o -E  'ProtoID=[0-9]{4}' *.log|awk -F= '{print $2}'|sort|uniq
1001
1004
2001
2005
2008
2201
2202
2205
2208
3001
3002
3012
3013
```

应该是OpenD中的问题。在log中可以看到，OpenD中收到了成交信息，然后只调用了`SendTrdAccPushToClient`，并没有调用`SendToClient ConnID=11653650236842690211 ProtoID=2218`
```
07-10 09:51:03(1531187466) | 83892 | GTW | Info | APISever | Trd_UpdateOrderFill::Response ProtobufBodyToJson: {"retType":0,"s2c":{"header":{"trdEnv":1,"accID":"281756455990244260","trdMarket":1},"orderFill":{"trdSide":2,"fillID":"2067285472261460914","fillIDEx":"221053975","orderID":"4909405056552652981","orderIDEx":"212140597","code":"61248","name":"恒指法兴九十牛B.C","qty":10000,"price":0.112,"createTime":"2018-07-10 09:51:04","counterBrokerID":512,"counterBrokerName":"E.O.Ltd."}}}
07-10 09:51:03(1531187466) | 83892 | GTW | Info | APISever | APIServerConn SendTrdAccPushToClient AccID=281756455990244260
07-10 09:51:03(1531187466) | 83892 | GTW | Info | APISever | Trd_UpdateOrder::Response ProtobufBodyToJson: {"retType":0,"s2c":{"header":{"trdEnv":1,"accID":"281756455990244260","trdMarket":1},"order":{"trdSide":2,"orderType":1,"orderStatus":11,"orderID":"4909405056552652981","orderIDEx":"212140597","code":"61248","name":"恒指法兴九十牛B.C","qty":10000,"price":0.112,"createTime":"2018-07-10 09:50:17","updateTime":"2018-07-10 09:51:04","fillQty":10000,"fillAvgPrice":0.112}}}
07-10 09:51:03(1531187466) | 83892 | GTW | Info | APISever | APIServerConn SendTrdAccPushToClient AccID=281756455990244260
```

## TradeOrderHandler也有问题
TradeOrderHandler似乎也有问题，调用次数不够。下面是我统计的`ProtoID与收到次数`表。可以看到OrderBookHandler(3013)是正常的，TradeOrderHandler(2008)只有20个，而我成交了60单。
```
ProtoID: 收到次数
 '1001': 846,
 '1004': 13953,
 '2001': 298,
 '2005': 32,
 '2008': 20,
 '2201': 248,
 '2202': 284,
 '2205': 1803,
 '2208': 8,
 '3001': 370,
 '3002': 370,
 '3012': 78,
 '3013': 46326
```

**Comment by summer-wu** [comment]
这是log（位于`$HOME/.com.futunn.FutuOpenD/log`）。我把含有手机号的那个log删掉了
[Log.zip](https://github.com/FutunnOpen/futuquant/files/2180229/Log.zip)

**Comment by FutunnOpen** [comment]
测试未能复现问题，请确认一下你那边的脚本是否已经成功调用set_handler(TradeDealTest())。
